[
  {
    "title": "The Crimson River",
    "author": "Elena Vance",
    "genre": "Mystery",
    "publisher": "Penguin Random House",
    "edition": "First Edition",
    "price": 799.50,
    "availableCopies": 15,
    "totalCopies": 25,
    "description": "A thrilling mystery that will keep you on the edge of your seat."
  },
  {
    "title": "Echoes of Eternity",
    "author": "Julian Croft",
    "genre": "Science Fiction",
    "publisher": "Starlight Books",
    "edition": "Hardcover",
    "price": 1250.00,
    "availableCopies": 30,
    "totalCopies": 30,
    "description": "A journey across galaxies to uncover the secrets of the universe."
  },
  {
    "title": "The Silent Garden",
    "author": "Aria Bell",
    "genre": "Fantasy",
    "publisher": "Evergreen Press",
    "edition": "Paperback",
    "price": 550.00,
    "availableCopies": 45,
    "totalCopies": 50,
    "description": "In a world of magic and myth, a hidden garden holds the key to salvation."
  },
  {
    "title": "Whispers of the Void",
    "author": "Marcus Stone",
    "genre": "Horror",
    "publisher": "Crimson Quill",
    "edition": "Collector's Edition",
    "price": 2500.00,
    "availableCopies": 5,
    "totalCopies": 10,
    "description": "An ancient evil awakens to haunt the residents of a small town."
  },
  {
    "title": "A Legacy of Ash",
    "author": "Silas Knight",
    "genre": "Historical Fiction",
    "publisher": "Anchor Publishing",
    "edition": "Hardcover",
    "price": 999.00,
    "availableCopies": 18,
    "totalCopies": 20,
    "description": "A gripping tale set during the turmoil of a forgotten war."
  },
  {
    "title": "The Last Voyager",
    "author": "Clara Reed",
    "genre": "Adventure",
    "publisher": "Odyssey Publications",
    "edition": "Paperback",
    "price": 650.75,
    "availableCopies": 22,
    "totalCopies": 40,
    "description": "The final journey of a legendary explorer into uncharted territories."
  },
  {
    "title": "City of Chrome",
    "author": "Leo Foster",
    "genre": "Dystopian",
    "publisher": "North Peak Publishing",
    "edition": "First Edition",
    "price": 850.00,
    "availableCopies": 12,
    "totalCopies": 30,
    "description": "In a futuristic metropolis, one person dares to defy the system."
  },
  {
    "title": "Beneath a Scarlet Sky",
    "author": "Maya Kim",
    "genre": "Romance",
    "publisher": "Silverleaf Books",
    "edition": "Anniversary Edition",
    "price": 700.00,
    "availableCopies": 35,
    "totalCopies": 35,
    "description": "A heart-wrenching love story that transcends time and conflict."
  },
  {
    "title": "The Serpent's Throne",
    "author": "Owen Grant",
    "genre": "Fantasy",
    "publisher": "Celestial Books",
    "edition": "Hardcover",
    "price": 1400.00,
    "availableCopies": 9,
    "totalCopies": 15,
    "description": "A battle for power, magic, and the throne of a mythical kingdom."
  },
  {
    "title": "Mind Machines",
    "author": "Nina Hayes",
    "genre": "Science Fiction",
    "publisher": "Beacon Publishing",
    "edition": "Paperback",
    "price": 900.25,
    "availableCopies": 28,
    "totalCopies": 50,
    "description": "Exploring the consequences of artificial intelligence achieving consciousness."
  },
  {
    "title": "The Glass Butterfly",
    "author": "Aria Bell",
    "genre": "Mystery",
    "publisher": "Penguin Random House",
    "edition": "Paperback",
    "price": 620.00,
    "availableCopies": 50,
    "totalCopies": 60,
    "description": "A detective chases a killer who leaves behind a single, delicate clue."
  },
  {
    "title": "Fires of the Old World",
    "author": "Silas Knight",
    "genre": "Historical Fiction",
    "publisher": "Anchor Publishing",
    "edition": "Hardcover",
    "price": 1100.00,
    "availableCopies": 14,
    "totalCopies": 20,
    "description": "Chronicles the rise and fall of a powerful ancient empire."
  },
  {
    "title": "Quantum Entanglement",
    "author": "Nina Hayes",
    "genre": "Non-Fiction",
    "publisher": "Beacon Publishing",
    "edition": "First Edition",
    "price": 1800.00,
    "availableCopies": 10,
    "totalCopies": 10,
    "description": "A deep dive into the strange and fascinating world of quantum physics."
  },
  {
    "title": "The Gilded Cage",
    "author": "Clara Reed",
    "genre": "Thriller",
    "publisher": "Odyssey Publications",
    "edition": "Paperback",
    "price": 750.00,
    "availableCopies": 33,
    "totalCopies": 40,
    "description": "A psychological thriller about a woman trapped in a web of lies."
  },
  {
    "title": "Starfall",
    "author": "Julian Croft",
    "genre": "Science Fiction",
    "publisher": "Starlight Books",
    "edition": "Hardcover",
    "price": 1350.00,
    "availableCopies": 25,
    "totalCopies": 25,
    "description": "The story of humanity's first contact with an alien civilization."
  },
  {
    "title": "Lost in the Lavender Fields",
    "author": "Maya Kim",
    "genre": "Romance",
    "publisher": "Silverleaf Books",
    "edition": "Paperback",
    "price": 499.00,
    "availableCopies": 60,
    "totalCopies": 75,
    "description": "Two lost souls find each other in the picturesque countryside of France."
  },
  {
    "title": "The Oracle's Prophecy",
    "author": "Owen Grant",
    "genre": "Fantasy",
    "publisher": "Celestial Books",
    "edition": "Collector's Edition",
    "price": 2750.00,
    "availableCopies": 4,
    "totalCopies": 8,
    "description": "A young hero is chosen to fulfill a prophecy that could save or doom the world."
  },
  {
    "title": "Concrete Jungle",
    "author": "Leo Foster",
    "genre": "Dystopian",
    "publisher": "North Peak Publishing",
    "edition": "Paperback",
    "price": 825.50,
    "availableCopies": 19,
    "totalCopies": 30,
    "description": "A tale of survival in a world where nature has reclaimed the cities."
  },
  {
    "title": "The Shadow in the Mirror",
    "author": "Marcus Stone",
    "genre": "Horror",
    "publisher": "Crimson Quill",
    "edition": "Hardcover",
    "price": 1050.00,
    "availableCopies": 7,
    "totalCopies": 15,
    "description": "A cursed mirror reflects more than just the person standing in front of it."
  },
  {
    "title": "Secrets of the Silk Road",
    "author": "Elena Vance",
    "genre": "Adventure",
    "publisher": "Evergreen Press",
    "edition": "First Edition",
    "price": 950.00,
    "availableCopies": 21,
    "totalCopies": 25,
    "description": "An archaeologist uncovers a conspiracy hidden for centuries along the ancient trade route."
  },
  {
    "title": "The Alchemist's Heir",
    "author": "Aria Bell",
    "genre": "Fantasy",
    "publisher": "Celestial Books",
    "edition": "Hardcover",
    "price": 1150.00,
    "availableCopies": 18,
    "totalCopies": 22,
    "description": "The descendant of a famed alchemist discovers their ancestor's dangerous secret."
  },
  {
    "title": "Project Chimera",
    "author": "Nina Hayes",
    "genre": "Science Fiction",
    "publisher": "Starlight Books",
    "edition": "Paperback",
    "price": 880.00,
    "availableCopies": 35,
    "totalCopies": 40,
    "description": "A top-secret genetics experiment goes horribly wrong."
  },
  {
    "title": "The Last Lighthouse",
    "author": "Clara Reed",
    "genre": "Mystery",
    "publisher": "Penguin Random House",
    "edition": "Paperback",
    "price": 699.00,
    "availableCopies": 40,
    "totalCopies": 50,
    "description": "The mysterious disappearance of a lighthouse keeper on a remote island."
  },
  {
    "title": "Embers of a Revolution",
    "author": "Silas Knight",
    "genre": "Historical Fiction",
    "publisher": "Anchor Publishing",
    "edition": "Hardcover",
    "price": 1200.00,
    "availableCopies": 10,
    "totalCopies": 15,
    "description": "A novel depicting the lives of ordinary people during a great uprising."
  },
  {
    "title": "The Somnambulist",
    "author": "Marcus Stone",
    "genre": "Horror",
    "publisher": "Crimson Quill",
    "edition": "First Edition",
    "price": 999.00,
    "availableCopies": 9,
    "totalCopies": 12,
    "description": "A man discovers his sleepwalking activities are far more sinister than he imagined."
  },
  {
    "title": "Where the Sunflowers Grow",
    "author": "Maya Kim",
    "genre": "Romance",
    "publisher": "Silverleaf Books",
    "edition": "Paperback",
    "price": 525.00,
    "availableCopies": 55,
    "totalCopies": 60,
    "description": "A summer romance blossoms in the golden fields of Tuscany."
  },
  {
    "title": "Code of the Ancients",
    "author": "Julian Croft",
    "genre": "Adventure",
    "publisher": "Odyssey Publications",
    "edition": "Hardcover",
    "price": 1050.00,
    "availableCopies": 20,
    "totalCopies": 25,
    "description": "A linguist races against time to decipher a code that predicts global catastrophes."
  },
  {
    "title": "The Iron Empire",
    "author": "Leo Foster",
    "genre": "Dystopian",
    "publisher": "North Peak Publishing",
    "edition": "Hardcover",
    "price": 1100.50,
    "availableCopies": 15,
    "totalCopies": 20,
    "description": "A rebellion brews within the walls of a totalitarian steampunk city."
  },
  {
    "title": "A Symphony of Stars",
    "author": "Owen Grant",
    "genre": "Science Fiction",
    "publisher": "Beacon Publishing",
    "edition": "Collector's Edition",
    "price": 3000.00,
    "availableCopies": 3,
    "totalCopies": 5,
    "description": "An epic space opera involving warring galactic empires and ancient cosmic beings."
  },
  {
    "title": "The Baker Street Enigma",
    "author": "Elena Vance",
    "genre": "Mystery",
    "publisher": "Evergreen Press",
    "edition": "Paperback",
    "price": 720.00,
    "availableCopies": 30,
    "totalCopies": 35,
    "description": "A modern detective uses classic methods to solve a seemingly impossible crime."
  },
  {
    "title": "The Dragon's Pearl",
    "author": "Aria Bell",
    "genre": "Fantasy",
    "publisher": "Celestial Books",
    "edition": "Paperback",
    "price": 650.00,
    "availableCopies": 45,
    "totalCopies": 50,
    "description": "A young girl embarks on a quest to find a mythical pearl to save her village."
  },
  {
    "title": "Cybernetic Dawn",
    "author": "Nina Hayes",
    "genre": "Science Fiction",
    "publisher": "Starlight Books",
    "edition": "Hardcover",
    "price": 1300.00,
    "availableCopies": 22,
    "totalCopies": 25,
    "description": "The story of the first fully sentient android and its fight for rights."
  },
  {
    "title": "Whiskey and Regret",
    "author": "Marcus Stone",
    "genre": "Thriller",
    "publisher": "Crimson Quill",
    "edition": "First Edition",
    "price": 900.00,
    "availableCopies": 13,
    "totalCopies": 20,
    "description": "A disgraced ex-cop gets a chance at redemption by solving a cold case."
  },
  {
    "title": "The Paris Bookseller",
    "author": "Clara Reed",
    "genre": "Historical Fiction",
    "publisher": "Anchor Publishing",
    "edition": "Paperback",
    "price": 780.00,
    "availableCopies": 38,
    "totalCopies": 40,
    "description": "A story of love, literature, and resistance in Nazi-occupied Paris."
  },
  {
    "title": "Isle of the Lost",
    "author": "Julian Croft",
    "genre": "Adventure",
    "publisher": "Odyssey Publications",
    "edition": "Hardcover",
    "price": 950.00,
    "availableCopies": 18,
    "totalCopies": 30,
    "description": "A group of treasure hunters gets stranded on a mysterious, uncharted island."
  },
  {
    "title": "Neon Gods",
    "author": "Leo Foster",
    "genre": "Dystopian",
    "publisher": "North Peak Publishing",
    "edition": "Paperback",
    "price": 850.00,
    "availableCopies": 25,
    "totalCopies": 30,
    "description": "In a city run by corporations, faith is placed in digital deities."
  },
  {
    "title": "A Vow of Roses",
    "author": "Maya Kim",
    "genre": "Romance",
    "publisher": "Silverleaf Books",
    "edition": "Hardcover",
    "price": 1000.00,
    "availableCopies": 15,
    "totalCopies": 15,
    "description": "A historical romance between a noblewoman and her forbidden love."
  },
  {
    "title": "The Cartographer's Secret",
    "author": "Elena Vance",
    "genre": "Mystery",
    "publisher": "Penguin Random House",
    "edition": "First Edition",
    "price": 820.00,
    "availableCopies": 19,
    "totalCopies": 25,
    "description": "An ancient map reveals a conspiracy that changes the course of history."
  },
  {
    "title": "The Seventh Sorcerer",
    "author": "Owen Grant",
    "genre": "Fantasy",
    "publisher": "Celestial Books",
    "edition": "Hardcover",
    "price": 1450.00,
    "availableCopies": 10,
    "totalCopies": 12,
    "description": "The final installment in the epic saga of the sorcerers' council."
  },
  {
    "title": "The House on Willow Lane",
    "author": "Marcus Stone",
    "genre": "Horror",
    "publisher": "Evergreen Press",
    "edition": "Paperback",
    "price": 680.00,
    "availableCopies": 33,
    "totalCopies": 40,
    "description": "A family moves into their dream home, unaware of its dark past."
  },
  {
    "title": "The Expanse Between Us",
    "author": "Nina Hayes",
    "genre": "Science Fiction",
    "publisher": "Starlight Books",
    "edition": "Hardcover",
    "price": 1275.00,
    "availableCopies": 28,
    "totalCopies": 30,
    "description": "A love story set on a generation ship traveling to a distant star."
  },
  {
    "title": "Chronicles of the Sunstone",
    "author": "Aria Bell",
    "genre": "Fantasy",
    "publisher": "Celestial Books",
    "edition": "Paperback",
    "price": 700.00,
    "availableCopies": 50,
    "totalCopies": 50,
    "description": "A group of heroes must reunite the pieces of a powerful, ancient artifact."
  },
  {
    "title": "The Romanov Conspiracy",
    "author": "Silas Knight",
    "genre": "Historical Fiction",
    "publisher": "Anchor Publishing",
    "edition": "Collector's Edition",
    "price": 2200.00,
    "availableCopies": 5,
    "totalCopies": 7,
    "description": "A historical thriller exploring the mysteries surrounding the last Russian tsars."
  },
  {
    "title": "Zero Point",
    "author": "Julian Croft",
    "genre": "Thriller",
    "publisher": "Odyssey Publications",
    "edition": "Paperback",
    "price": 800.00,
    "availableCopies": 25,
    "totalCopies": 35,
    "description": "An elite special forces team must stop a terrorist from unleashing a deadly weapon."
  },
  {
    "title": "Beneath the City of Lies",
    "author": "Leo Foster",
    "genre": "Dystopian",
    "publisher": "North Peak Publishing",
    "edition": "First Edition",
    "price": 950.00,
    "availableCopies": 11,
    "totalCopies": 20,
    "description": "An investigator uncovers the dark truth that holds his perfect society together."
  },
  {
    "title": "The Last Song of Summer",
    "author": "Maya Kim",
    "genre": "Romance",
    "publisher": "Silverleaf Books",
    "edition": "Paperback",
    "price": 550.00,
    "availableCopies": 60,
    "totalCopies": 60,
    "description": "A poignant story of a summer fling that turns into a lifelong love."
  },
  {
    "title": "The Shogun's Blade",
    "author": "Owen Grant",
    "genre": "Historical Fiction",
    "publisher": "Anchor Publishing",
    "edition": "Hardcover",
    "price": 1150.00,
    "availableCopies": 16,
    "totalCopies": 20,
    "description": "A tale of honor, betrayal, and swordsmanship in feudal Japan."
  },
  {
    "title": "The Crimson Labyrinth",
    "author": "Elena Vance",
    "genre": "Mystery",
    "publisher": "Evergreen Press",
    "edition": "Hardcover",
    "price": 980.00,
    "availableCopies": 20,
    "totalCopies": 25,
    "description": "A detective gets trapped in a deadly game designed by a brilliant serial killer."
  },
  {
    "title": "Echoes of the Deep",
    "author": "Clara Reed",
    "genre": "Adventure",
    "publisher": "Odyssey Publications",
    "edition": "Paperback",
    "price": 725.00,
    "availableCopies": 29,
    "totalCopies": 40,
    "description": "A deep-sea exploration team discovers a lost civilization at the bottom of the ocean."
  },
  {
    "title": "Asylum of Whispers",
    "author": "Marcus Stone",
    "genre": "Horror",
    "publisher": "Crimson Quill",
    "edition": "Paperback",
    "price": 710.00,
    "availableCopies": 14,
    "totalCopies": 20,
    "description": "Urban explorers get more than they bargained for in an abandoned mental asylum."
  },
  {
    "title": "The Art of War: A Modern Take",
    "author": "Silas Knight",
    "genre": "Non-Fiction",
    "publisher": "Beacon Publishing",
    "edition": "Hardcover",
    "price": 1500.00,
    "availableCopies": 8,
    "totalCopies": 10,
    "description": "Applying ancient strategies to modern business, politics, and life."
  },
  {
    "title": "Synthetic Souls",
    "author": "Nina Hayes",
    "genre": "Science Fiction",
    "publisher": "Starlight Books",
    "edition": "Paperback",
    "price": 920.00,
    "availableCopies": 31,
    "totalCopies": 35,
    "description": "In the future, memories can be bought and sold, but at what cost?"
  },
  {
    "title": "The Starlight Serenade",
    "author": "Maya Kim",
    "genre": "Romance",
    "publisher": "Silverleaf Books",
    "edition": "First Edition",
    "price": 750.00,
    "availableCopies": 25,
    "totalCopies": 25,
    "description": "Two rival musicians find harmony and love while competing for a prestigious award."
  },
  {
    "title": "The Forgotten Kingdom",
    "author": "Aria Bell",
    "genre": "Fantasy",
    "publisher": "Celestial Books",
    "edition": "Hardcover",
    "price": 1250.00,
    "availableCopies": 12,
    "totalCopies": 18,
    "description": "An ancient map leads a young adventurer to a kingdom thought only to exist in myth."
  },
  {
    "title": "The Compliance Protocol",
    "author": "Leo Foster",
    "genre": "Dystopian",
    "publisher": "North Peak Publishing",
    "edition": "Paperback",
    "price": 875.00,
    "availableCopies": 17,
    "totalCopies": 25,
    "description": "In a society that demands conformity, one person's individuality is a crime."
  },
  {
    "title": "The Venice Vendetta",
    "author": "Elena Vance",
    "genre": "Thriller",
    "publisher": "Penguin Random House",
    "edition": "Hardcover",
    "price": 1050.00,
    "availableCopies": 20,
    "totalCopies": 22,
    "description": "An art historian uncovers a deadly secret hidden within a Renaissance masterpiece."
  },
  {
    "title": "King of the Undying",
    "author": "Owen Grant",
    "genre": "Fantasy",
    "publisher": "Celestial Books",
    "edition": "Collector's Edition",
    "price": 2800.00,
    "availableCopies": 2,
    "totalCopies": 6,
    "description": "A necromancer's quest to control the realms of both the living and the dead."
  },
  {
    "title": "The Solitude of Stars",
    "author": "Julian Croft",
    "genre": "Science Fiction",
    "publisher": "Starlight Books",
    "edition": "Paperback",
    "price": 950.00,
    "availableCopies": 30,
    "totalCopies": 40,
    "description": "The lonely journey of an astronaut on a solo mission to the edge of the solar system."
  },
  {
    "title": "The Tudor Rose",
    "author": "Silas Knight",
    "genre": "Historical Fiction",
    "publisher": "Anchor Publishing",
    "edition": "Hardcover",
    "price": 1100.00,
    "availableCopies": 14,
    "totalCopies": 18,
    "description": "A story of political intrigue and romance in the court of Henry VIII."
  },
  {
    "title": "The Marionette Maker",
    "author": "Marcus Stone",
    "genre": "Horror",
    "publisher": "Crimson Quill",
    "edition": "First Edition",
    "price": 975.00,
    "availableCopies": 10,
    "totalCopies": 15,
    "description": "A toymaker's creations have a life of their own, and they are not friendly."
  },
  {
    "title": "Journey to the Crystal Caves",
    "author": "Clara Reed",
    "genre": "Adventure",
    "publisher": "Odyssey Publications",
    "edition": "Paperback",
    "price": 690.00,
    "availableCopies": 35,
    "totalCopies": 45,
    "description": "Explorers search for a legendary cave system said to have healing powers."
  },
  {
    "title": "Love in the Time of Robots",
    "author": "Nina Hayes",
    "genre": "Romance",
    "publisher": "Silverleaf Books",
    "edition": "Paperback",
    "price": 600.00,
    "availableCopies": 40,
    "totalCopies": 50,
    "description": "Can a human and a highly advanced AI truly fall in love?"
  },
  {
    "title": "The Obsidian Mirror",
    "author": "Aria Bell",
    "genre": "Fantasy",
    "publisher": "Evergreen Press",
    "edition": "Hardcover",
    "price": 1200.00,
    "availableCopies": 16,
    "totalCopies": 20,
    "description": "A magical mirror shows not what you are, but what you could become."
  },
  {
    "title": "The Last Outpost",
    "author": "Leo Foster",
    "genre": "Dystopian",
    "publisher": "North Peak Publishing",
    "edition": "Hardcover",
    "price": 1050.00,
    "availableCopies": 18,
    "totalCopies": 25,
    "description": "The story of a small community of survivors in a post-apocalyptic world."
  },
  {
    "title": "A Whisper of Treason",
    "author": "Silas Knight",
    "genre": "Historical Fiction",
    "publisher": "Anchor Publishing",
    "edition": "Paperback",
    "price": 820.00,
    "availableCopies": 28,
    "totalCopies": 30,
    "description": "A spy navigates the dangerous political landscape of Elizabethan England."
  },
  {
    "title": "The Goliath Project",
    "author": "Julian Croft",
    "genre": "Thriller",
    "publisher": "Starlight Books",
    "edition": "Paperback",
    "price": 850.00,
    "availableCopies": 33,
    "totalCopies": 40,
    "description": "A rogue scientist creates a biological weapon that threatens the entire planet."
  },
  {
    "title": "The Sakura Bloom",
    "author": "Maya Kim",
    "genre": "Romance",
    "publisher": "Silverleaf Books",
    "edition": "Hardcover",
    "price": 950.00,
    "availableCopies": 20,
    "totalCopies": 20,
    "description": "A fleeting romance blossoms during the cherry blossom festival in Kyoto."
  },
  {
    "title": "The Cryptic Cipher",
    "author": "Elena Vance",
    "genre": "Mystery",
    "publisher": "Penguin Random House",
    "edition": "Paperback",
    "price": 730.00,
    "availableCopies": 27,
    "totalCopies": 35,
    "description": "A series of murders are all linked by a strange, unbreakable code."
  },
  {
    "title": "The Warden of the West",
    "author": "Owen Grant",
    "genre": "Fantasy",
    "publisher": "Celestial Books",
    "edition": "Hardcover",
    "price": 1350.00,
    "availableCopies": 11,
    "totalCopies": 15,
    "description": "A lone warrior must defend the borderlands against an encroaching dark army."
  },
  {
    "title": "Harvest of the Damned",
    "author": "Marcus Stone",
    "genre": "Horror",
    "publisher": "Crimson Quill",
    "edition": "Hardcover",
    "price": 1000.00,
    "availableCopies": 9,
    "totalCopies": 12,
    "description": "A small farming town's annual harvest festival takes a terrifying turn."
  },
  {
    "title": "The Andromeda Anomaly",
    "author": "Nina Hayes",
    "genre": "Science Fiction",
    "publisher": "Beacon Publishing",
    "edition": "First Edition",
    "price": 1100.00,
    "availableCopies": 18,
    "totalCopies": 20,
    "description": "A research team studying a galactic anomaly discovers it's not a natural phenomenon."
  },
  {
    "title": "The Path of the Wanderer",
    "author": "Clara Reed",
    "genre": "Adventure",
    "publisher": "Odyssey Publications",
    "edition": "Paperback",
    "price": 700.00,
    "availableCopies": 32,
    "totalCopies": 40,
    "description": "A personal journey of self-discovery across the world's most breathtaking landscapes."
  },
  {
    "title": "The City of Sighs",
    "author": "Leo Foster",
    "genre": "Dystopian",
    "publisher": "North Peak Publishing",
    "edition": "Paperback",
    "price": 890.00,
    "availableCopies": 21,
    "totalCopies": 30,
    "description": "In a city where emotions are suppressed by law, a rebellion of feeling begins."
  },
  {
    "title": "The Highlander's Heart",
    "author": "Maya Kim",
    "genre": "Romance",
    "publisher": "Silverleaf Books",
    "edition": "Collector's Edition",
    "price": 1800.00,
    "availableCopies": 6,
    "totalCopies": 10,
    "description": "A sweeping romance set in the rugged, beautiful Scottish Highlands."
  },
  {
    "title": "The Ghost of Blackwood Manor",
    "author": "Aria Bell",
    "genre": "Mystery",
    "publisher": "Evergreen Press",
    "edition": "Hardcover",
    "price": 990.00,
    "availableCopies": 23,
    "totalCopies": 25,
    "description": "A classic whodunit with a supernatural twist in a gothic English manor."
  },
  {
    "title": "The Viking's Curse",
    "author": "Silas Knight",
    "genre": "Historical Fiction",
    "publisher": "Anchor Publishing",
    "edition": "Paperback",
    "price": 840.00,
    "availableCopies": 26,
    "totalCopies": 30,
    "description": "A Viking warrior's journey is plagued by a curse from a powerful seer."
  },
  {
    "title": "The Phoenix Protocol",
    "author": "Julian Croft",
    "genre": "Thriller",
    "publisher": "Odyssey Publications",
    "edition": "Hardcover",
    "price": 1150.00,
    "availableCopies": 19,
    "totalCopies": 25,
    "description": "An intelligence agency must activate a dormant deep-cover agent to prevent a world war."
  },
  {
    "title": "The Sunken City of Ys",
    "author": "Owen Grant",
    "genre": "Fantasy",
    "publisher": "Celestial Books",
    "edition": "Paperback",
    "price": 750.00,
    "availableCopies": 38,
    "totalCopies": 45,
    "description": "An underwater expedition discovers the legendary, magically-preserved city of Ys."
  },
  {
    "title": "The Midnight Carnival",
    "author": "Marcus Stone",
    "genre": "Horror",
    "publisher": "Crimson Quill",
    "edition": "Paperback",
    "price": 720.00,
    "availableCopies": 15,
    "totalCopies": 20,
    "description": "A carnival that appears only at midnight holds terrifying secrets for its patrons."
  },
  {
    "title": "The Terraforming of Mars",
    "author": "Nina Hayes",
    "genre": "Non-Fiction",
    "publisher": "Beacon Publishing",
    "edition": "Hardcover",
    "price": 1900.00,
    "availableCopies": 7,
    "totalCopies": 10,
    "description": "The science, ethics, and future of making the Red Planet habitable."
  },
  {
    "title": "The Last Train to Istanbul",
    "author": "Elena Vance",
    "genre": "Mystery",
    "publisher": "Penguin Random House",
    "edition": "Paperback",
    "price": 780.00,
    "availableCopies": 30,
    "totalCopies": 35,
    "description": "A spy game unfolds on a luxury train journey across Europe in the 1930s."
  },
  {
    "title": "The Winter Queen",
    "author": "Aria Bell",
    "genre": "Fantasy",
    "publisher": "Evergreen Press",
    "edition": "Hardcover",
    "price": 1280.00,
    "availableCopies": 17,
    "totalCopies": 20,
    "description": "A powerful queen of ice and snow must save her kingdom from an encroaching fire demon."
  },
  {
    "title": "The Paradox of Time",
    "author": "Julian Croft",
    "genre": "Science Fiction",
    "publisher": "Starlight Books",
    "edition": "First Edition",
    "price": 1000.00,
    "availableCopies": 20,
    "totalCopies": 25,
    "description": "A time traveler must fix the past without erasing their own existence."
  },
  {
    "title": "The Revolution's Daughter",
    "author": "Silas Knight",
    "genre": "Historical Fiction",
    "publisher": "Anchor Publishing",
    "edition": "Paperback",
    "price": 800.00,
    "availableCopies": 24,
    "totalCopies": 30,
    "description": "The life of a young woman growing up during the French Revolution."
  },
  {
    "title": "The Silent Scream",
    "author": "Marcus Stone",
    "genre": "Thriller",
    "publisher": "Crimson Quill",
    "edition": "Hardcover",
    "price": 950.00,
    "availableCopies": 13,
    "totalCopies": 18,
    "description": "A detective hunts a killer who targets victims who are unable to speak."
  },
  {
    "title": "The Savannah Proposal",
    "author": "Maya Kim",
    "genre": "Romance",
    "publisher": "Silverleaf Books",
    "edition": "Paperback",
    "price": 580.00,
    "availableCopies": 45,
    "totalCopies": 50,
    "description": "A wildlife photographer and a conservationist fall in love on the African plains."
  },
  {
    "title": "The Amazon Expedition",
    "author": "Clara Reed",
    "genre": "Adventure",
    "publisher": "Odyssey Publications",
    "edition": "Hardcover",
    "price": 1100.00,
    "availableCopies": 22,
    "totalCopies": 25,
    "description": "A perilous journey deep into the Amazon rainforest in search of a lost city of gold."
  },
  {
    "title": "The Grid",
    "author": "Leo Foster",
    "genre": "Dystopian",
    "publisher": "North Peak Publishing",
    "edition": "First Edition",
    "price": 920.00,
    "availableCopies": 16,
    "totalCopies": 20,
    "description": "In a world where everyone is connected to a global network, logging off is a death sentence."
  },
  {
    "title": "The Mage's Gambit",
    "author": "Owen Grant",
    "genre": "Fantasy",
    "publisher": "Celestial Books",
    "edition": "Paperback",
    "price": 790.00,
    "availableCopies": 35,
    "totalCopies": 40,
    "description": "A cunning mage plays a dangerous game of politics and power in the royal court."
  },
  {
    "title": "The Quantum Thief",
    "author": "Nina Hayes",
    "genre": "Science Fiction",
    "publisher": "Starlight Books",
    "edition": "Hardcover",
    "price": 1250.00,
    "availableCopies": 20,
    "totalCopies": 22,
    "description": "A master thief uses quantum technology to pull off impossible heists."
  },
  {
    "title": "The Cairo Deception",
    "author": "Elena Vance",
    "genre": "Mystery",
    "publisher": "Evergreen Press",
    "edition": "Paperback",
    "price": 760.00,
    "availableCopies": 29,
    "totalCopies": 35,
    "description": "An archaeologist in 1920s Egypt realizes her latest discovery is at the center of a modern conspiracy."
  },
  {
    "title": "The Last Samurai's Vow",
    "author": "Silas Knight",
    "genre": "Historical Fiction",
    "publisher": "Anchor Publishing",
    "edition": "Hardcover",
    "price": 1180.00,
    "availableCopies": 12,
    "totalCopies": 15,
    "description": "The poignant story of a samurai warrior during the end of the samurai era."
  },
  {
    "title": "The Weeping Willow",
    "author": "Marcus Stone",
    "genre": "Horror",
    "publisher": "Crimson Quill",
    "edition": "Collector's Edition",
    "price": 2400.00,
    "availableCopies": 4,
    "totalCopies": 8,
    "description": "The ghost of a woman haunts the ancient willow tree where she met her tragic end."
  },
  {
    "title": "The Heart of the Volcano",
    "author": "Clara Reed",
    "genre": "Adventure",
    "publisher": "Odyssey Publications",
    "edition": "Paperback",
    "price": 710.00,
    "availableCopies": 31,
    "totalCopies": 40,
    "description": "A volcanologist must retrieve a vital piece of research from an erupting volcano."
  },
  {
    "title": "The Final Sonata",
    "author": "Maya Kim",
    "genre": "Romance",
    "publisher": "Silverleaf Books",
    "edition": "Hardcover",
    "price": 980.00,
    "availableCopies": 24,
    "totalCopies": 25,
    "description": "A love story between a brilliant composer and his muse, told through their letters and music."
  }
]
